### ISSUE TITLE
Keyboard setting broken

### ISSUE THREAD

**Issue by ghost** [radxa-pkg/rsetup#20]
When installing a copy of the current (38) debian 4se cli image and running rsetup, the keyboard localization settings fail.
The package keyboard-configuration is missing from the system image.

**Comment by RadxaYuntian** [comment]
Apparently even when that package is installed [the change will not persist](https://askubuntu.com/a/342099). Gonna need to see how to properly implement and test this since we only have US layout here.

**Comment by RadxaYuntian** [comment]
For some reason running `dpkg-reconfigure keyboard-configuration` will NOT popup the keyboard selection dialog again. Disable this feature for now.
