### ISSUE TITLE
文件选择界面无法滚动并超出范围

### ISSUE THREAD

**Issue by CodeChenL** [radxa-pkg/rsetup#21]
界面为选择第三方dtbo，如下图：
![enable-user-led3](https://github.com/radxa-pkg/rsetup/assets/43897062/3fb5a558-b601-4fac-aefe-cf13d771655b)

**Comment by RadxaYuntian** [comment]
本地xterm或者串口终端无法复现：
![image](https://github.com/radxa-pkg/rsetup/assets/95260730/16b3e5f3-8c21-4f0a-b5e0-ff3c8778335f)
可以看到旁边有个进度条

**Comment by CodeChenL** [comment]
我这边使用windows terminal和windterm都不行

**Comment by CodeChenL** [comment]
这是部分设置
![image](https://github.com/radxa-pkg/rsetup/assets/43897062/c75497fc-b308-4eb4-8838-6257ada0f2b2)
![image](https://github.com/radxa-pkg/rsetup/assets/43897062/053f3642-b6ec-46c5-97d5-915d4ef94835)
![image](https://github.com/radxa-pkg/rsetup/assets/43897062/81032c21-8bbc-4b83-a9fd-6c4c1e13691c)

**Comment by CodeChenL** [comment]
修正了一下第一张图

**Comment by RadxaYuntian** [comment]
echo $TERM 看看，顺便试试 sudo TERM=linux rsetup

**Comment by CodeChenL** [comment]
> echo $TERM 看看，顺便试试 sudo TERM=linux rsetup

还是一样

**Comment by CodeChenL** [comment]
而且我发现进了连接网络界面无法退出tui，选择Quit后又会重新进入nmtui
![image](https://github.com/radxa-pkg/rsetup/assets/43897062/6004d0a2-6a35-4573-bdf5-4f65b2e3ca89)

**Comment by RadxaYuntian** [comment]
github release装最新的试试，已经修复了

**Comment by CodeChenL** [comment]
> github release装最新的试试，已经修复了

确实修复了

**Comment by CodeChenL** [comment]
我这边用xterm还是一样
![image](https://github.com/radxa-pkg/rsetup/assets/43897062/d04d660c-f416-41de-bf63-b0cee01d8012)

**Comment by CodeChenL** [comment]
xterm -verison是330

**Comment by CodeChenL** [comment]
好的

**Comment by CodeChenL** [comment]
> 有时间麻烦看看这个问题是否依然存在

使用板子系统自带xterm问题依旧存在

**Comment by RadxaYuntian** [comment]
可能是TERM的环境变量问题，xterm可能支持的字符少，无法显示侧边的滚动条
在其他的终端模拟器里面模拟xterm的TERM看看

**Comment by CodeChenL** [comment]
使用Konsole和uxterm也是一样的情况

**Comment by RadxaYuntian** [comment]
可能是Debian 12更新了whiptail？https://salsa.debian.org/mckinstry/newt/-/blob/debian/0.52.23-1/CHANGES?ref_type=tags#L2

**Comment by CodeChenL** [comment]
> 可能是Debian 12更新了whiptail？https://salsa.debian.org/mckinstry/newt/-/blob/debian/0.52.23-1/CHANGES?ref_type=tags#L2

debian12正常，应该是
