### ISSUE TITLE
Reset overlays无效

### ISSUE THREAD

**Issue by CodeChenL** [radxa-pkg/rsetup#23]
如果已经启用了dtbo，Reset overlays无效，dtbo启用依旧存在

**Comment by CodeChenL** [comment]
也不会清除安装的第三方dtbo

**Comment by RadxaYuntian** [comment]
说明需要更新了，最开始的确是全部干掉，后来考虑到我们内核升级时也会执行reset_overlays，如果用户已经配置好了一些硬件启动必须的overlay是不能直接全部禁用的。
