### ISSUE TITLE
update spi bootloader failed

### ISSUE THREAD

**Issue by shawnchainw** [radxa-pkg/rsetup#30]
![image](https://github.com/radxa-pkg/rsetup/assets/137867758/70415a15-e790-4368-b1ee-181bdd16a23f)
When I don't have the relevant overlay enabled, I use "rsetup" to update my SPI flash, but it fails without providing sufficient information. There should be more detailed prompts instead of just displaying a failure message.

**Comment by RadxaYuntian** [comment]
Fixed in https://github.com/radxa-pkg/rsetup/commit/8cb4ac0947c6227ffecc3a2d5ee63d2ca82c59da#diff-deb00be173b7526f14e122e7784780460f19b50cf27f39e4219ce098b2a0114dR78-R81 & https://github.com/radxa-repo/bsp/commit/05195f741a908c6c297924999217977087fd1c81.
