### ISSUE TITLE
parsing error when both a.dtbo and a.dtbo.disabled are present

### ISSUE THREAD

**Issue by nascs** [radxa-pkg/rsetup#46]
Searching available overlays may take a while, please wait...
jq: error: syntax error, unexpected '/', expecting FORMAT or QQSTRING_START (Unix shell quoting issues?) at <top-level>, line 1:
.[0].metadata./boot/dtbo/meson-g12-pwmao-d.dtbo.disabled[0]              
jq: 1 compile error
jq: error: syntax error, unexpected '/', expecting FORMAT or QQSTRING_START (Unix shell quoting issues?) at <top-level>, line 1:
.[0].metadata./boot/dtbo/meson-g12-pwmao-d.dtbo.disabled[0]              
jq: 1 compile error
/usr/lib/rsetup/tui/overlay/overlay.sh: line 172: package[0]: unbound variable

**Comment by nascs** [comment]
当 /boot/dtbo/ 目录里面同时存在 a.dtbo and a.dtbo.disabled 的时候，rsetup 解析会报错导致崩溃。假设 /boot/dtbo 里面已经存在一个 a.dtbo.disabled，如果再往 /boot/dtbo/ 里面放 a.dtbo 文件，这时候再用 rsetup 去解析的时候会导致 rsetup 崩溃。

![rsetup_error](https://github.com/radxa-pkg/rsetup/assets/105425502/b12bf0d9-7590-466b-94c1-bf51fcbd8de1)

**Comment by nascs** [comment]
当 /boot/dtbo/ 目录里面同时存在 a.dtbo 和 a.dtbo.disabled 的时候，rsetup 解析会报错导致崩溃。假设 /boot/dtbo 里面已经存在一个 a.dtbo.disabled，如果再往 /boot/dtbo/ 里面放 a.dtbo 文件，这时候再用 rsetup 去解析的时候会导致 rsetup 崩溃。

![rsetup_error](https://github.com/radxa-pkg/rsetup/assets/105425502/c87b687e-b5ba-4088-996c-89ac9d333d39)

**Comment by nascs** [comment]
往 /boot/dtbo/ 里面放 a.dtbo 文件，这个时候无论 rsetup 开启是否，再用 rsetup 去解析，就会报错而崩溃。重点是同时存在 a.dtbo 和 a.dtbo.disabled。

**Comment by nascs** [comment]
更新升级后正常，这个 issue 可以关了

**Comment by RadxaYuntian** [comment]
所以不是跟你说了要更新么？
