### ISSUE TITLE
rsetup is not working

### ISSUE THREAD

**Issue by makoto-tsudo** [radxa-pkg/rsetup#52]
```
$ sudo rsetup
/usr/lib/librtui/utils/utils.sh: line 3: ERROR_REQUIRE_PARAMETER: readonly variable
```

I reported issue to rdxa-repo too.
https://github.com/radxa-repo/bookworm/issues/2

**Comment by RadxaYuntian** [comment]
Can you provide the rsetup version you installed on your system? You can check with `apt list --installed rsetup`.

**Comment by RadxaYuntian** [comment]
Nevermind I have reproduced this.

**Comment by RadxaYuntian** [comment]
Please run following command and check if rsetup is working again:

```bash
wget https://github.com/radxa-pkg/librtui/releases/download/0.1.3/librtui_0.1.3_all.deb
sudo dpkg -i librtui_0.1.3_all.deb
```

**Comment by makoto-tsudo** [comment]
LGTM

**Comment by RadxaYuntian** [comment]
I'm currently publishing this new version to our apt repos. Thanks for your report.
