### ISSUE TITLE
添加自动登陆的支持

### ISSUE THREAD

**Issue by RadxaYuntian** [radxa-pkg/rsetup#61]
此前自动登陆都是让用户通过KDE的系统设置应用来完成的，但现在使用gdm后就失效了，需要在rsetup里面添加

- [ ] 支持串口agetty
- [ ] 支持无桌面的tty1
- [ ] 支持lightdm
- [ ] 支持sddm
- [ ] 支持gdm
- [ ] 有CLI方便从其他脚本调用

可以参考[这里](http://gitlab.vamrs.com/yuntian/xpcba/blob/update-readme/create_image.sh#L28-68)

**Comment by CodeChenL** [comment]
是一键开关还是，还是开关颗粒度到列出的每一项

**Comment by RadxaYuntian** [comment]
应该要到每一项

**Comment by RadxaYuntian** [comment]
https://gitlab.manjaro.org/manjaro-arm/applications/manjaro-arm-tools/-/blob/master/lib/functions.sh?ref_type=heads#L508

**Comment by RadxaYuntian** [comment]
gdm3在debian下应该是读取/etc/gdm3:https://salsa.debian.org/gnome-team/gdm/-/blob/debian/latest/debian/rules?ref_type=heads#L52

**Comment by RadxaYuntian** [comment]
哦再看了下代码，就是要修改/etc/gdm3/daemon.conf，不会去读取别的文件

**Comment by CodeChenL** [comment]
> 哦再看了下代码，就是要修改/etc/gdm3/daemon.conf，不会去读取别的文件

刚刚试了/usr/share/gdm/gdm.schemas也有效

**Comment by RadxaYuntian** [comment]
两个都有效，但/usr/share/gdm/gdm.schemas是distro提供的配置文件，是不适合放这种用户自定义配置的
x11那个属于我们的全局修改，用户是不应该去改动的，就可以放到usr/share里面

**Comment by CodeChenL** [comment]
https://github.com/radxa-pkg/rsetup/pull/62，应该可以关闭了
