### ISSUE TITLE
Hardware-Video capture devices不能自动终止

### ISSUE THREAD

**Issue by RadxaYuntian** [radxa-pkg/rsetup#79]
目前的命令好像是在录制视频，不会自动停止。只有按下Ctrl+C后才会继续执行，然后提示图片的路径。

**Comment by CodeChenL** [comment]
是要加上录制时间吗

**Comment by RadxaYuntian** [comment]
不是，是这个功能应该只是简单照一张照片确认硬件没问题就行，不应该卡住录制视频

**Comment by RadxaYuntian** [comment]
是在串口登陆时遇到的

**Comment by CodeChenL** [comment]
我试了一下是截图，但是需要ctrl+c手动暂停：
![image](https://github.com/user-attachments/assets/f3eecf6f-f948-4c45-82a3-4d79b60ce4cd)
![image](https://github.com/user-attachments/assets/23c76089-5492-4712-a010-e7f3195f48d4)
过程看起来是录视频，其实是手动选择时间截图，需要改成自动截图，不用手动干预吗

**Comment by RadxaYuntian** [comment]
以前好像没有这个问题，能找5.10老系统啥的确认一下么？

**Comment by CodeChenL** [comment]
看了一下 blame https://github.com/radxa-pkg/rsetup/blame/main/src/usr/lib/rsetup/tui/hardware/hardware.sh ，除了改动一个设备变量和将videoconvert改成autovideoconvert，这个命令是没变过的，可能是gst本身的版本更迭导致的？

**Comment by RadxaYuntian** [comment]
我记得之前测试这个功能的时候是会自动停止的。那看一下现在该怎么做吧
