### ISSUE TITLE
add information about rsetup version

### ISSUE THREAD

**Issue by onlineapps-cloud** [radxa-pkg/rsetup#80]
hi, why you don't show version of this tool? you have great place in about page to put it!
`apt list --installed rsetup` this is not friendly, and not all users know about this command!
![1000000391](https://github.com/user-attachments/assets/b352bb1f-1eeb-4380-8ef0-501727989143)

**Comment by RadxaYuntian** [comment]
The version info is not part of the source code but the [package code](https://github.com/radxa-pkg/rsetup/blob/main/debian/changelog), so there is no straight forward way to embedded this information.

I also don't think user should care about their `rsetup` version that much. We publish the latest version on our own package repository, so it is not like Debian where the user is stuck with a specific version for the whole distro release. When in doubt just do a system update, and that will get you the latest version of `rsetup`.
