### ISSUE TITLE
Problems encountered with ROCK 4SE Debian 11 KDE using rsetup

### ISSUE THREAD

**Issue by Vamrs-zxy** [radxa-pkg/rsetup#9]
1. ssh cannot be enabled. You must use "sudo /etc/init.d/ssh start" to start ssh.
2. Unable to change user password. Select Change Password and press Enter to display The password has been changed.

**Comment by RadxaYuntian** [comment]
1 is non-issue (new system has ssh disabled by default), while I can't reproduce 2 in the current release of `rsetup`.
